Working electron-redux implementation
karczewskiPiotr/vnlab-tool pull request #8
Opened 2020-11-11 12:00 UTC by lukasz-starosta

## Description

## Linked issues
closes #7 

## Correct PR Checklist
- [x] I have linked an issue (use e.g. `closes #1`)
- [x] I have assigned Reviewers
- [x] I have assigned a Team label
- [x] I have assigned an Description label
- [x] I have assigned a Project
- [x] I have assigend a Milestone

2020-11-11 12:01 UTC, lukasz-starosta commented on src/main/index.ts
> +const store = configureStore('main');
This is the store initialization for the `main` process

2020-11-11 12:12 UTC, lukasz-starosta commented on src/main/index.ts
> +  store.subscribe(() => console.log('action received in main'))
This is temporary -> will be deleted. It logs the text in the console (where we run `npm start`)

2020-11-11 12:13 UTC, lukasz-starosta commented on src/main/index.ts
> +app.on('browser-window-blur', () => store.dispatch(exampleAliasedAction('text')))
A simple action dispatched from the `main` process.  
Notice that it is aliased -> is only being executed in the `main` process, and the result of which is being broadcast to the `renderer` processes.

2020-11-11 12:14 UTC, lukasz-starosta commented on src/renderer/components/app/app.tsx
> +store.subscribe(() => console.log('action received in renderer'))
Temporary -> subscribes to actions that are received in the `renderer` process

2020-11-11 12:15 UTC, lukasz-starosta commented on src/renderer/components/description/description.tsx
> +    <button onClick={() => dispatch(exampleAction('example action'))}>Dispatch Example action</button>
This will dispatch an example action received both in `main` and `renderer`

2020-11-11 12:15 UTC, lukasz-starosta commented on src/renderer/components/description/description.tsx
> +    <button onClick={() => dispatch(exampleLocalAction('example action'))}>Dispatch Example local action</button>
This will dispatch an example action received only in `renderer` (local)

2020-11-11 12:16 UTC, lukasz-starosta commented on src/shared/actions/example.ts
> +)
Notice three different notations for actions.
1. received in both processes
2. `renderer` -> `renderer`, used for e.g. UI state like `isPanelOpen`
3. `main` -> `renderer`

2020-11-11 12:16 UTC, lukasz-starosta commented on src/shared/reducers/example.ts
> +export default function todos(state = initialState, action: any) {
example reducer, can be removed, just showcasing

2020-11-11 14:51 UTC, 217853 commented
I looked through it, looks fine.

2020-11-11 19:48 UTC, karczewskiPiotr requested changes
All works nicely but since we settled on using [Toolkit](https://redux-toolkit.js.org/) to simplify Redux in the long run, I've rewritten wee bit of the implementation and examples to use utilize it (see #9).

2020-11-11 21:25 UTC, karczewskiPiotr approved these changes

2020-11-12 15:28 UTC, lukasz-starosta commented on src/main/index.ts
> +  store.subscribe(() => console.log('action received in main'));
This should be deleted, logs the text in our terminal (not browser console, as it is the main process)

2020-11-12 15:28 UTC, lukasz-starosta commented on src/renderer/components/app/app.tsx
> +store.subscribe(() => console.log('action received in renderer'));
This should also be deleted, logs the text in browser console

2020-11-12 15:31 UTC, szymonrucinski approved these changes
Looks good to me 👍🏻

2020-11-12 18:57 UTC, ProudBloom approved these changes
Everything seems fine 😃

2020-11-12 21:31 UTC, 217853 approved these changes
Nicely configured. 
Approved

2020-11-12 22:08 UTC, szymonrucinski approved these changes

2020-11-13 21:43 UTC, Eleara approved these changes

2020-11-14 14:40 UTC, merged